from mxnet import nd
x=nd.arange(12)
print(x)
print(x.shape)
print(x.size)
x = x.reshape((3, 4))
print(x)
x=nd.zeros((2, 3, 4))
print(x)
y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(y)
x=nd.random.normal(0, 1, shape=(3, 4))
print(x)
print(x+y)
print(x*y)
print(x/y)
print(y.exp())